version: '3.8'

services:
  backend:
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    ports:
      - "8085:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/src
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
